import sqlite3
from langchain_community.utilities import SQLDatabase
from langchain_classic.chains import create_sql_query_chain
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
import os
from dotenv import load_dotenv

# Ensure we use the fresh API key
load_dotenv(override=True)

def query_database_with_ai(user_question):
    # Connect to the SQLite database generated by File 2
    db = SQLDatabase.from_uri("sqlite:///hr_enterprise.db")
    
    # Initialize the LLM (Temperature 0 ensures it doesn't hallucinate code)
    llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)
    
    # Strict prompt engineering for the AI (Now includes top_k safety guardrail)
    template = '''Given an input question, create a syntactically correct SQLite query to query a SQLite database.

You have access to tools for interacting with a SQLite database. Only use the below tools. Only use the information returned by the below tools to construct your final answer.

Unless told otherwise, do not make any assumptions about what the table looks like and what columns exist.
Get the schema and sample data first.

If the question does not seem related to the database schema, just return "I don\'t know" as the answer.

Here is the relevant table info: {table_info}

Question: {input}
SQLQuery:'''
    prompt = PromptTemplate(input_variables=['input', 'top_k', 'table_info'], template=template)
    prompt = prompt.partial(top_k=10)
    
    # Create the SQL construction chain
    execute_query = create_sql_query_chain(llm, db, prompt=prompt)
    
    try:
        # Generate the SQL
        sql_query = execute_query.invoke({"question": user_question})
        clean_sql = sql_query.replace("```sql", "").replace("```", "").strip()
        
        # Execute against the database
        conn = sqlite3.connect('hr_enterprise.db')
        cursor = conn.cursor()
        cursor.execute(clean_sql)
        result = cursor.fetchall()
        conn.close()
        
        return clean_sql, result
    except Exception as e:
        return None, f"Error: {e}"

# --- Quick Test Block ---
# This will only run if we execute this file directly, allowing us to test the brain.
if __name__ == "__main__":
    print("Waking up the AI and asking it a question...")
    question = "How many employees are in the Manufacturing department?"
    generated_sql, db_result = query_database_with_ai(question)
    
    print(f"\nAI Wrote This SQL: \n{generated_sql}")
    print(f"\nDatabase Answered With: \n{db_result}")