import sqlite3
from langchain_community.utilities import SQLDatabase
from langchain_classic.chains import create_sql_query_chain
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
import os
from dotenv import load_dotenv

# Ensure we use the fresh API key
load_dotenv(override=True)

def query_database_with_ai(user_question):
    # Connect to the SQLite database generated by File 2
    db = SQLDatabase.from_uri("sqlite:///hr_enterprise.db")
    
    # Initialize the LLM (Temperature 0 ensures it doesn't hallucinate code)
    llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)
    
    # Strict prompt engineering for the AI (Now includes top_k safety guardrail)
    template = '''Given an input question, create a syntactically correct SQLite query.
    Unless the user specifies otherwise, limit your query to at most {top_k} results.
    Only use the following tables: {table_info}
    Question: {input}'''
    prompt = PromptTemplate.from_template(template)
    
    # Create the SQL construction chain
    execute_query = create_sql_query_chain(llm, db, prompt=prompt)
    
    try:
        # Generate the SQL
        sql_query = execute_query.invoke({"question": user_question})
        clean_sql = sql_query.replace("```sql", "").replace("```", "").strip()
        
        # Execute against the database
        conn = sqlite3.connect('hr_enterprise.db')
        cursor = conn.cursor()
        cursor.execute(clean_sql)
        result = cursor.fetchall()
        conn.close()
        
        return clean_sql, result
    except Exception as e:
        return None, f"Error: {e}"

# --- Quick Test Block ---
# This will only run if we execute this file directly, allowing us to test the brain.
if __name__ == "__main__":
    print("Waking up the AI and asking it a question...")
    question = "How many employees are in the Manufacturing department?"
    generated_sql, db_result = query_database_with_ai(question)
    
    print(f"\nAI Wrote This SQL: \n{generated_sql}")
    print(f"\nDatabase Answered With: \n{db_result}")